id = "mcp-server-llm-rules"
name = "llm-rules MCP Server"
description = "Model Context Protocol Server to supply Cursor rules to Zed via llm-rules"
version = "0.1.0"
schema_version = 1
authors = ["Hunter Haugen <hunter@haugen.email>"]
repository = "https://github.com/hunner/mcp-server-llm-rules"

[context_servers.mcp-server-llm-rules]
name = "llm-rules MCP Server"
